allow testing the release artifacts in a PR

diff --git a/.github/workflows/pypipublish.yml b/.github/workflows/pypipublish.yml
--- a/.github/workflows/pypipublish.yml
+++ b/.github/workflows/pypipublish.yml
@@ -3,27 +3,69 @@ name: Upload Python Package on PyPI
 on:
   release:
     types: [published]
+  pull_request:
+    branches:
+      - main
 
 jobs:
+  build-artifacts:
+    runs-on: ubuntu-latest
+    if: |
+      github.repository == 'xarray-contrib/xdggs'
+      && (
+        github.event_name == 'release'
+        || (
+          github.event_name == 'pull_request'
+          && contains(github.event.pull_request.labels.*.name, 'release')
+        )
+      )
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+        with:
+          persist-credentials: false
+      - name: Set up Python
+        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
+        with:
+          python-version: "3.x"
+      - name: Install publish dependencies
+        run: python -m pip install build twine
+      - name: Build package
+        run: python -m build . -o dist
+      - name: Check built artifacts
+        run: |
+          python -m twine check --strict dist/*
+          pwd
+          if [ -f dist/xdggs-0.1.*.tar.gz ]; then
+            echo "❌ INVALID VERSION NUMBER"
+            exit 1
+          else
+            echo "✅ Looks good"
+          fi
+      - name: Upload artifacts
+        if: github.event_name == 'release'
+        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
+        with:
+          name: releases
+          path: dist
+
   deploy:
     runs-on: ubuntu-latest
+    if: github.event_name == 'release'
+
     environment:
       name: pypi
       url: https://pypi.org/p/xdggs
     permissions:
       id-token: write
     steps:
-      - name: Checkout
-        uses: actions/checkout@v6
-      - name: Set up Python
-        uses: actions/setup-python@v6
+      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # 7.0.0
         with:
-          python-version: "3.x"
-      - name: Install publish dependencies
-        run: python -m pip install build
-      - name: Build package
-        run: python -m build . -o py_dist
+          name: releases
+          path: dist
+
       - name: Publish package to PyPI
         uses: pypa/gh-action-pypi-publish@release/v1
         with:
-          packages-dir: py_dist/
+          packages-dir: dist/
